"""auto-vote

Revision ID: acb2de10cf98
Revises: 8938ca389889
Create Date: 2025-11-30 09:51:02.156047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb2de10cf98'
down_revision: Union[str, Sequence[str], None] = '8938ca389889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['chats_orm.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_orm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')

